### ISSUE TITLE
specifying a language environment with ANSI C locale

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-files#35]
We need to add [LC_ALL=C](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) to `rultor.yml` merge script and make it work.
e.g.
```yaml
merge:
  script: |
    LC_ALL=C mvn clean install -Pqulice --errors -Dstyle.color=never
```
